services:
  - docker

matrix:
  fast-finish: true
  include:
    - env:
      - DB_VERSION: mysql:5.5
    - env:
      - DB_VERSION: mysql:5.6
    - env:
      - DB_VERSION: mysql:5.7
    - env:
      - DB_VERSION: mysql:8
    - env:
      - DB_VERSION: mysql:latest
    - env:
      - DB_VERSION: mariadb:5.5
    - env:
      - DB_VERSION: mariadb:10.2
    - env:
      - DB_VERSION: mariadb:10.3
    - env:
      - DB_VERSION: mariadb:10.4
    - env:
      - DB_VERSION: mariadb:latest

before_install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - export PATH="/home/travis/.deno/bin:$PATH"
  
script:
  - docker run -d -p $DB_PORT:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true $DB_VERSION
  - sleep 30
  - deno run --allow-all ./test.ts
